### ISSUE TITLE
[BUG] Crashes rainmeter since one of last MS update

### ISSUE THREAD

**Issue by Fred-Vatin** [flyinghyrax/rm-drivelist-plugin#4]
Rainmeter version | OS | DriveList version
------------------ | ---- | ----
4.0.0.2746  | Win 10 x64 pro (french) 14393 | 1.1.0.0 (2014.06.28)

## Steps to reproduce

Load a skin that use the plugin

## Results

Rainmeter crashes instantly

## Causes

It happens just after a Microsoft Update that involved a PC reboot.

One of the plausible responsable update:
- [KB4023834](http://support.microsoft.com/help/4023834): Servicing Stack Update
- [KB3186568](https://support.microsoft.com/en-us/help/3186568/the-microsoft-net-framework-4-7-for-windows-10-version-1607-and-window) .NET Framework 4.7
---
I hope you can reproduce and fix it. It is a valuable plugin that I've used for years.

**Comment by Fred-Vatin** [comment]
It seems it is fixed now with the KB4022715

**Comment by flyinghyrax** [comment]
@freMea thank you for the thorough and well-organized bug report! I'm glad a later update seems to have fixed the problem for you. Do let me know if it becomes an issue again. I haven't had much Rainmeter time recently, but I will try to take a look if needed.
